<div class="ves-inner">
<?php
$_vesData = $this->helper('Ves\Themesettings\Helper\Data');
$_ves = $this->helper('Ves\Themesettings\Helper\Theme');
$staticblock = $_ves->getFooterCfg("footer_center_settings/staticblock");
$custom_html = $_ves->getFooterCfg("footer_center_settings/custom_html");
if($staticblock){
	if(is_numeric($staticblock)){
		echo $this->getStaticBlock($staticblock);
	}else{
		echo $_vesData->filter($custom_html);
	}
}
?>
</div>