<?php
/**
 * Copyright © 2015 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
 <!--<div class="toolbar-sorter sorter">
    <label class="sorter-label" for="sorter"><?php echo __('Sort By') ?></label>
    <select id="sorter" data-role="sorter" class="sorter-options">
        <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
            <option value="<?php echo $_key; ?>"
                <?php if ($block->isOrderCurrent($_key)): ?>
                    selected="selected"
                <?php endif; ?>
                >
                <?php echo $block->escapeHtml(__($_order)) ?>
            </option>
        <?php endforeach; ?>
    </select>
    <?php if ($block->getCurrentDirection() == 'desc'): ?>
        <a title="<?php echo __('Set Ascending Direction') ?>" href="#" class="action sorter-action sort-desc" data-role="direction-switcher" data-value="asc">
            <span><?php echo __('Set Ascending Direction') ?></span>
        </a>
    <?php else: ?>
        <a title="<?php echo __('Set Descending Direction') ?>" href="#" class="action sorter-action sort-asc" data-role="direction-switcher" data-value="desc">
            <span><?php echo __('Set Descending Direction') ?></span>
        </a>
    <?php endif; ?> 
</div>-->

<div class="switcher sorter">
    <?php $currentOrderKey = ''; ?>
    <div class="switcher" >
        <!-- <span class="switcher-title hidden-xs"><?php echo __('Sort By: ') ?></span> -->
        <div class="actions dropdown options switcher-options">
         <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
            <?php if ($block->isOrderCurrent($_key)): ?>
                <?php $currentOrderKey = $_key; ?>
                <div class="action toggle switcher-trigger">
                    <strong><span><?php echo $block->escapeHtml(__($_order)) ?></span></strong>
                </div>
            <?php endif; ?>
        <?php endforeach; ?>
        <ul class="dropdown switcher-dropdown">
              <?php foreach ($block->getAvailableOrders() as $_key => $_order): ?>
                <li value="<?php echo $_key; ?>" >
                    <?php
                    $url = $this->getPagerUrl();
                    $orderUrl = Toolbar::ORDER_PARAM_NAME . '=' . $currentOrderKey;
                    $url1 = str_replace($orderUrl, Toolbar::ORDER_PARAM_NAME . '=' . $_key, $url);
                    if (strpos($url, $orderUrl) === false) {
                        $url1 = $url . '?' . Toolbar::ORDER_PARAM_NAME . '=' . $_key;
                    }
                    ?>
                    <a href="<?php echo $url1 ?>" title="<?php echo $block->escapeHtml(__($_order)) ?>">
                        <?php echo $block->escapeHtml(__($_order)) ?>
                    </a>
                </li>
            <?php endforeach; ?>
        </ul>
</div>
</div>
</div>
<?php

?>
