<?php
/**
 * Copyright © 2016 Magento. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

?>
<?php
/**
 * Product list toolbar
 *
 * @var $block \Magento\Catalog\Block\Product\ProductList\Toolbar
 */
use Magento\Catalog\Model\Product\ProductList\Toolbar;
?>
<?php if ($block->getCollection()->getSize()): ?>
    <div class="toolbar toolbar-products" data-mage-init='<?php /* @escapeNotVerified */ echo $block->getWidgetOptionsJson(); ?>'>
	    <?php echo $block->getPagerHtml() ?>
	    <div class="col-lg-2 col-md-2 col-sm-12 no-padding">
			<?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/amount.phtml')) ?>
		</div>
		<div class="col-lg-4 col-md-4 col-sm-6">
			<?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/limiter.phtml')) ?>
		</div>
        <div class="col-lg-4 col-md-4 col-sm-6">
			<?php if ($block->isExpanded()): ?>
				<?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/sorter.phtml')) ?>
			<?php endif; ?>
		</div>
		
		<div class="col-lg-2 col-md-2 col-sm-12 no-padding">
			<?php if ($block->isExpanded()): ?>
				<?php include ($block->getTemplateFile('Magento_Catalog::product/list/toolbar/viewmode.phtml')) ?>
			<?php endif; ?>
        </div> 
    </div>
<?php endif ?>
